### PR TITLE
Merge Kolasu 1.5

### PR DESCRIPTION
**Pull request by alessiostalla**
I've created this PR because for some reason the build fails locally with Gradle but IDEA doesn't report any errors, so I want to run CI checks before actually pushing this to main.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Alessio, sorry but I just understood now that you are merging the recent changes into main (Kolasu 1.6). I think I did that a couple days ago. I understood that you wanted me to do that based on the conversation we had in https://github.com/Strumenta/kolasu/pull/356. I am sorry for the duplicated work.

**Comment by alessiostalla** [comment]
Oh OK :)

**Comment by alessiostalla** [comment]
So, is this good to merge in your opinion?

**Comment by ftomassetti** [comment]
Yes, thank you for looking into this!

**Pull request merged**
