### PR TITLE
Making the core module NOT depend on ANTLR

### LINKED ISSUE #105: Consider moving ANTLR out of the core module

### PR DESCRIPTION
**Pull request by ftomassetti**
This will permit in the future to implement parsers or lexers using something different from ANTLR. I basically removed the dependency from ANTLR in core and moved all the classes that did not compile to the new `antlr` module. It required very few changes. I also renamed the packages involving antlr to include the word `antlr`

Fix #105 

Please note that this is intended to be merged in the Kolasu 1.6 branch, not in the master branch.

### CODE REVIEW

**Comment by loradd** [comment]
What about ANTLR parse tree nodes as `origin`? I might be missing something here, are we using `Origin` nodes and setting the text property or some kind of ANTLR node wrapper?

**Comment by ftomassetti** [comment]
> What about ANTLR parse tree nodes as origin? I might be missing something here, are we using Origin nodes and setting the text property or some kind of ANTLR node wrapper?

`ParseTreeOrigin` moved to the ANTLR module. When using an ANTLR parser everything should work as before this PR: one would just need to include also the kolasu-antlr module. However if someone build a Kolasu node without using ANTLR then it will need to provide another subclass of Origin. Does this make sense?

**Comment by loradd** [comment]
Yes, it makes sense to me! Nice :)

**Comment by alessiostalla** [comment]
Makes sense & it's also roughly the process we've followed in Tylasu (though there it's still a single module with multiple entry points).

**Review by loradd — APPROVED** [review]
Looks good!

**Comment by ftomassetti** [comment]
Thank you!

**Pull request merged**
