### PR TITLE
Transformers: allow to opt out of setting children 

### PR DESCRIPTION
**Pull request by alessiostalla**
Addresses issue #160

### CODE REVIEW

**Comment by ftomassetti** [comment]
I have two comments:
1) I think a comment about why this is useful could help. The reason is that the use-case for nodes that wrap other nodes (explained in the connected issue) is not that well-known, I think
2) I tend to think about all the nodeProperties have playing different roles: some contains children while other contains attributes. So if I read "skipChildren" I would expect that we only skip the properties that deal with nodes but we still consider the other properties (the one setting attributes: strings, ints, booleans, enums, etc.)

**Comment by alessiostalla** [comment]
Regarding point 1 this is useful whenever the "node factory" already takes care of populating a node's children. This is the case of the SAS parser as explained in the issue, but also potentially when using "identity transformers". However, the issue only appears when one uses the `@Mapped` annotation, that's why it's not obvious. I've added more details to issue #160. Long-term, I think `@Mapped` should be deprecated and removed; however, the issue still remains **if** we want to continue supporting transforming from nested objects (e.g. child "a" of the transformed node is the transformation of child "b" of child "c" of the source node).

Regarding 2 transformers only deal with children, not with properties. Properties have to be set by the "Node factory" either manually or by reflection, but they're out of the transformer's scope.

**Comment by ftomassetti** [comment]
Regarding point 1, sorry, I meant adding a comment in the code, so that a user of the library would know when to use that flag

Regarding point 2, ok, understood

**Comment by ftomassetti** [comment]
+1, thanks Alessio

**Review by ftomassetti — APPROVED** [review]

**Pull request merged**
