### PR TITLE
Reimplement transform

### PR DESCRIPTION
**Pull request by matozoid**
#18 - if I understand correctly, the normal `transform` is like `transformChildren` plus `transform(this)`.

If #21 is accepted, this will have to be updated. There will be `transform` and `transformInPlace`

### CODE REVIEW

**Comment by matozoid** [comment]
I seem to misunderstand transformChildren: does it only affect the direct children of the node? If so, where is the function that affects all descendants?

**Comment by ftomassetti** [comment]
Yes, it seems to affect only the direct children.
I think there is note an operation to transform all descendants. I think one could build it using `transformChildren` in the operation, making it recursive

**Comment by ftomassetti** [comment]
I think the initial use case was replacing a child in an AST which may be immutable

**Comment by matozoid** [comment]
Well, I made #23.

So, what exactly should `transform` do?

**Comment by ftomassetti** [comment]
Perhaps we should wait and merge the others PRs, as they would affect this one, correct?

**Comment by matozoid** [comment]
Okay, only this one left. If you had to Javadoc this function, what would it say?

**Comment by ftomassetti** [comment]
My Javadoc would say this:
```
Transform can be used to operate on a whole AST, transforming single nodes as desired.
Depending on the AST being modifiable or not the transformation can happen in place or not. In the former case the existing AST is modified directly, otherwise a new AST is generated to replace the previous one.
``

**Comment by ftomassetti** [comment]
Is this one blocked by something I should do @matozoid ?

**Comment by matozoid** [comment]
It's waiting for some kind of agreement or disagreement here: https://github.com/Strumenta/kolasu/issues/18 :-)

**Comment by ftomassetti** [comment]
ok, then I will continue discussion in #18 (done :D)

**Comment by matozoid** [comment]
@matozoid I need to finish this :-)

**Comment by matozoid** [comment]
Okay, naming is now in order :-)

**Pull request closed without merging**
